# Generated by Django 4.2.7 on 2025-09-02 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Identificador único do dispositivo ESP8266', max_length=100)),
                ('power_watts', models.FloatField(help_text='Leitura de potência em Watts')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da leitura')),
            ],
            options={
                'verbose_name': 'Leitura de Energia',
                'verbose_name_plural': 'Leituras de Energia',
                'ordering': ['-timestamp'],
            },
        ),
    ]
